kind = "DojoModel"
class_hash = "0x1b7c3d532ae3458e65862636c9bccbed8f58209e7317960aa20b0fa90068e03"
original_class_hash = "0x1b7c3d532ae3458e65862636c9bccbed8f58209e7317960aa20b0fa90068e03"
abi = "manifests/dev/abis/base/models/chain_monsters_models_index_monster.json"
name = "chain_monsters::models::index::monster"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "team_id"
type = "u8"
key = true

[[members]]
name = "id"
type = "u8"
key = true

[[members]]
name = "role"
type = "u8"
key = false

[[members]]
name = "clan"
type = "u8"
key = false

[[members]]
name = "health"
type = "u8"
key = false

[[members]]
name = "damage"
type = "u8"
key = false

[[members]]
name = "mana"
type = "u8"
key = false

[[members]]
name = "x"
type = "u8"
key = false

[[members]]
name = "y"
type = "u8"
key = false

[[members]]
name = "last_x"
type = "u8"
key = false

[[members]]
name = "last_y"
type = "u8"
key = false
