kind = "DojoModel"
class_hash = "0x2e0517a7a2ec6e0ca888074cdc6754fa8b2c974aad156ed976583f681ad8ce8"
original_class_hash = "0x2e0517a7a2ec6e0ca888074cdc6754fa8b2c974aad156ed976583f681ad8ce8"
abi = "manifests/dev/abis/base/models/chain_monsters_models_index_team.json"
name = "chain_monsters::models::index::team"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "index"
type = "u8"
key = true

[[members]]
name = "id"
type = "felt252"
key = false
