kind = "DojoModel"
class_hash = "0x7bd05a9b22d3483c7c258c76bb7888e11e42ba033c9f0ec9e383a7d8072deda"
original_class_hash = "0x7bd05a9b22d3483c7c258c76bb7888e11e42ba033c9f0ec9e383a7d8072deda"
abi = "manifests/dev/abis/base/models/chain_monsters_models_index_team.json"
name = "chain_monsters::models::index::team"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "id"
type = "u8"
key = true

[[members]]
name = "player_id"
type = "felt252"
key = false
