kind = "DojoModel"
class_hash = "0x50db134100615e1bdc7bbce17585d80e25bb81ff852ce43e9143a92152a45f8"
original_class_hash = "0x50db134100615e1bdc7bbce17585d80e25bb81ff852ce43e9143a92152a45f8"
abi = "manifests/dev/abis/base/models/chain_monsters_models_index_game.json"
name = "chain_monsters::models::index::game"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "over"
type = "bool"
key = false

[[members]]
name = "players"
type = "u8"
key = false

[[members]]
name = "player_count"
type = "u8"
key = false

[[members]]
name = "nonce"
type = "u16"
key = false

[[members]]
name = "seed"
type = "felt252"
key = false

[[members]]
name = "host"
type = "felt252"
key = false
