kind = "DojoModel"
class_hash = "0x1a9959b617c5152d78e9a3e7f4d36ee21df2598fdab856ce75cc7c6c180891a"
original_class_hash = "0x1a9959b617c5152d78e9a3e7f4d36ee21df2598fdab856ce75cc7c6c180891a"
abi = "manifests/dev/abis/base/models/chain_monsters_models_index_monster.json"
name = "chain_monsters::models::index::monster"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "team_id"
type = "u8"
key = true

[[members]]
name = "id"
type = "u8"
key = true

[[members]]
name = "health"
type = "u8"
key = false

[[members]]
name = "damage"
type = "u8"
key = false

[[members]]
name = "mana"
type = "u8"
key = false

[[members]]
name = "x"
type = "u8"
key = false

[[members]]
name = "y"
type = "u8"
key = false
