kind = "DojoModel"
class_hash = "0x11ad5627f8e26d3d40a7ee7ec0fec03fc117c8a47479a343a62679975c1cf34"
original_class_hash = "0x11ad5627f8e26d3d40a7ee7ec0fec03fc117c8a47479a343a62679975c1cf34"
abi = "manifests/dev/abis/base/models/chain_monsters_models_index_player.json"
name = "chain_monsters::models::index::player"

[[members]]
name = "id"
type = "felt252"
key = true

[[members]]
name = "name"
type = "felt252"
key = false
