kind = "DojoModel"
class_hash = "0x68c8bed975b3703aa77d7feedee2cbb439cad5a7de5635eb997e30627d9c671"
original_class_hash = "0x68c8bed975b3703aa77d7feedee2cbb439cad5a7de5635eb997e30627d9c671"
abi = "manifests/slot/abis/base/models/chain_monsters_models_index_player.json"
name = "chain_monsters::models::index::player"

[[members]]
name = "id"
type = "felt252"
key = true

[[members]]
name = "game_id"
type = "u32"
key = false

[[members]]
name = "name"
type = "felt252"
key = false
