kind = "DojoContract"
class_hash = "0x3a211add48066b5bb6103c674927fc8ae2195dacd70d2a8ebbc6af46b4a3f54"
original_class_hash = "0x3a211add48066b5bb6103c674927fc8ae2195dacd70d2a8ebbc6af46b4a3f54"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/chain_monsters_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "chain_monsters::systems::actions::actions"
