kind = "DojoContract"
class_hash = "0x6759c9865d1906a5027861b486dd627271c5359632c84684bab4b6f0f715773"
original_class_hash = "0x6759c9865d1906a5027861b486dd627271c5359632c84684bab4b6f0f715773"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/chain_monsters_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "chain_monsters::systems::actions::actions"
